a = "Mahi One"
print(len(a))
print(a.count("i"))  
print(a.startswith("M")) 
print(a.endswith("e"))
print(a.find("O"))    
print(a.rfind("O"))  
print(a.isalnum())  
print(a.isdigit())  
print(a.isalpha())    
print(a.islower())   
